SunSkyDemo/force-app/main/default/objects/Exception__c/Exception__c.object-meta.xml
<CustomObject>
    <description>Custom object used to store caught exceptions. Workflow rules can be leveraged to send email alerts upon record creation, and Process Builder can be used to send messages to a Chatter group or user.</description>
    <label>Exception</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Exception Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SunSkyDemo/force-app/main/default/objects/Exception__c/fields/Stack_Trace_String__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace_String__c</fullName>
    <label>Stack Trace String</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

SunSkyDemo/force-app/main/default/objects/Exception__c/fields/Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Type_Name__c</fullName>
    <label>Type Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AsyncException</fullName>
            </value>
            <value>
                <fullName>CalloutException</fullName>
            </value>
            <value>
                <fullName>DmlException</fullName>
            </value>
            <value>
                <fullName>EmailException</fullName>
            </value>
            <value>
                <fullName>InvalidParameterValueException</fullName>
            </value>
            <value>
                <fullName>JSONException</fullName>
            </value>
            <value>
                <fullName>LimitException</fullName>
            </value>
            <value>
                <fullName>ListException</fullName>
            </value>
            <value>
                <fullName>MathException</fullName>
            </value>
            <value>
                <fullName>NoAccessException</fullName>
            </value>
            <value>
                <fullName>NoDataFoundException</fullName>
            </value>
            <value>
                <fullName>NullPointerException</fullName>
            </value>
            <value>
                <fullName>QueryException</fullName>
            </value>
            <value>
                <fullName>RequiredFeatureMissing</fullName>
            </value>
            <value>
                <fullName>SearchException</fullName>
            </value>
            <value>
                <fullName>SecurityException</fullName>
            </value>
            <value>
                <fullName>SerializationException</fullName>
            </value>
            <value>
                <fullName>SObjectException</fullName>
            </value>
            <value>
                <fullName>StringException</fullName>
            </value>
            <value>
                <fullName>TypeException</fullName>
            </value>
            <value>
                <fullName>VisualforceException</fullName>
            </value>
            <value>
                <fullName>XmlException</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SunSkyDemo/force-app/main/default/classes/ExceptionUtilsTest.cls
@isTest
public class ExceptionUtilsTest {
    
    public static Account accountFail;
    public static Account accountSuccess;
    
    public static Integer eListSize;
   	public static String eCause;
    public static Decimal eLineNumber;
    public static String eMessage;
    public static String eStackTraceString;
    public static String eTypeName;
    
    static{
        
        accountFail = new Account();
        accountSuccess = new Account(Name = 'Account 2');
         
    }
    
    static testMethod void testAccountInsertFailure() {
        
        try {
            insert accountFail;
        } catch(Exception e) {
            ExceptionUtils.handleException(e, true);
            
            eCause = String.valueOf(e.getCause());
            eLineNumber = e.getLineNumber();
            eMessage = e.getMessage();
            eStackTraceString = e.getStackTraceString();
            eTypeName = e.getTypeName();
        }        
        
        List<Exception__c> exceptionCreated = [SELECT Id, Name, Cause__c, Line_Number__c, Message__c, Stack_Trace_String__c, Type_Name__c FROM Exception__c];
        
        eListSize = exceptionCreated.size();
        System.assertEquals(eListSize, 1);
        
        System.assertEquals(eCause, exceptionCreated[0].Cause__c);
        System.assertEquals(eLineNumber, exceptionCreated[0].Line_Number__c);
        System.assertEquals(eMessage, exceptionCreated[0].Message__c);
        System.assertEquals(eStackTraceString, exceptionCreated[0].Stack_Trace_String__c);
        System.assertEquals(eTypeName, exceptionCreated[0].Type_Name__c);
        
    }
    
    static testMethod void testAccountInsertSuccess() {
        
        try {
            insert accountSuccess;
        } catch(Exception e) {
            ExceptionUtils.handleException(e, true);
            
            eCause = String.valueOf(e.getCause());
            eLineNumber = e.getLineNumber();
            eMessage = e.getMessage();
            eStackTraceString = e.getStackTraceString();
            eTypeName = e.getTypeName();
        }        
        
        List<Exception__c> exceptionCreated = [SELECT Id, Name, Cause__c, Line_Number__c, Message__c, Stack_Trace_String__c, Type_Name__c FROM Exception__c];
        
        eListSize = exceptionCreated.size();
        System.assertEquals(eListSize, 0);
        
    }
    

    static testMethod void testAccountInsertSuccessEvent() {
        
        try {
            insert accountSuccess;
        } catch(Exception e) {
            // async test approach - we are using publish.. test the status after StopTest.    
            Test.startTest();
            ExceptionUtils.handleExceptionEvent(e);
            Test.StopTest();
            
            eCause = String.valueOf(e.getCause());
            eLineNumber = e.getLineNumber();
            eMessage = e.getMessage();
            eStackTraceString = e.getStackTraceString();
            eTypeName = e.getTypeName();
        }        
        
        List<Exception__c> exceptionCreated = [SELECT Id, Name, Cause__c, Line_Number__c, Message__c, Stack_Trace_String__c, Type_Name__c FROM Exception__c];
        
        eListSize = exceptionCreated.size();
        System.assertEquals(eListSize, 0);
        
    }

    static testMethod void testAccountInsertFailureEvent() {
        
        try {
            insert accountFail;
        } catch(Exception e) {
            // async test approach - we are using publish.. test the status after StopTest.    
            Test.startTest();
            ExceptionUtils.handleExceptionEvent(e);
            Test.StopTest();
            
            eCause = String.valueOf(e.getCause());
            eLineNumber = e.getLineNumber();
            eMessage = e.getMessage();
            eStackTraceString = e.getStackTraceString();
            eTypeName = e.getTypeName();
        }        
        
        List<Exception__c> exceptionCreated = [SELECT Id, Name, Cause__c, Line_Number__c, Message__c, Stack_Trace_String__c, Type_Name__c FROM Exception__c];
        
        eListSize = exceptionCreated.size();
        System.assertEquals(eListSize, 1);
        
        System.assertEquals(eCause, exceptionCreated[0].Cause__c);
        System.assertEquals(eLineNumber, exceptionCreated[0].Line_Number__c);
        System.assertEquals(eMessage, exceptionCreated[0].Message__c);
        System.assertEquals(eStackTraceString, exceptionCreated[0].Stack_Trace_String__c);
        System.assertEquals(eTypeName, exceptionCreated[0].Type_Name__c);
        
    }

}