SunSkyDemo/force-app/main/default/objects/Exception__c/Exception__c.object-meta.xml
<CustomObject>
    <description>Custom object used to store caught exceptions. Workflow rules can be leveraged to send email alerts upon record creation, and Process Builder can be used to send messages to a Chatter group or user.</description>
    <label>Exception</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Exception Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SunSkyDemo/force-app/main/default/objects/Exception__c/fields/Stack_Trace_String__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace_String__c</fullName>
    <label>Stack Trace String</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

SunSkyDemo/force-app/main/default/objects/Exception__c/fields/Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Type_Name__c</fullName>
    <label>Type Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AsyncException</fullName>
            </value>
            <value>
                <fullName>CalloutException</fullName>
            </value>
            <value>
                <fullName>DmlException</fullName>
            </value>
            <value>
                <fullName>EmailException</fullName>
            </value>
            <value>
                <fullName>InvalidParameterValueException</fullName>
            </value>
            <value>
                <fullName>JSONException</fullName>
            </value>
            <value>
                <fullName>LimitException</fullName>
            </value>
            <value>
                <fullName>ListException</fullName>
            </value>
            <value>
                <fullName>MathException</fullName>
            </value>
            <value>
                <fullName>NoAccessException</fullName>
            </value>
            <value>
                <fullName>NoDataFoundException</fullName>
            </value>
            <value>
                <fullName>NullPointerException</fullName>
            </value>
            <value>
                <fullName>QueryException</fullName>
            </value>
            <value>
                <fullName>RequiredFeatureMissing</fullName>
            </value>
            <value>
                <fullName>SearchException</fullName>
            </value>
            <value>
                <fullName>SecurityException</fullName>
            </value>
            <value>
                <fullName>SerializationException</fullName>
            </value>
            <value>
                <fullName>SObjectException</fullName>
            </value>
            <value>
                <fullName>StringException</fullName>
            </value>
            <value>
                <fullName>TypeException</fullName>
            </value>
            <value>
                <fullName>VisualforceException</fullName>
            </value>
            <value>
                <fullName>XmlException</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SunSkyDemo/force-app/main/default/objects/ExceptionEvent__e/ExceptionEvent__e.object-meta.xml
<CustomObject>
    <label>Exception Event</label>
    <pluralLabel>Exception Events</pluralLabel>
</CustomObject>

SunSkyDemo/force-app/main/default/objects/ExceptionEvent__e/fields/Cause__c.field-meta.xml
<CustomField>
    <fullName>Cause__c</fullName>
    <label>Cause</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

SunSkyDemo/force-app/main/default/objects/ExceptionEvent__e/fields/Stack_Trace_String__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace_String__c</fullName>
    <label>Stack Trace String</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

SunSkyDemo/force-app/main/default/objects/ExceptionEvent__e/fields/Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Type_Name__c</fullName>
    <label>Type Name</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

SunSkyDemo/force-app/main/default/classes/TestLogExceptionTrigger.cls
@isTest
private class TestLogExceptionTrigger {
    @isTest static void TestPostLogException() {
        // Test data setup
        // Create an account with an opportunity, and then try to delete it
        ExceptionEvent__e Log_e = new ExceptionEvent__e();
        Log_e.Cause__c = 'Cause 1';
        Log_e.Line_Number__c = 1;
        Log_e.Message__C ='Message1';
        Log_e.Stack_Trace_String__c='Stack Trace 1';
        Log_e.Type_Name__c = 'MathException';
        test.startTest();
        Database.SaveResult sr = Eventbus.publish(Log_e);
        test.stopTest();
        System.assertEquals(true, sr.isSuccess());
        List <Exception__c> logs = [Select Cause__C from Exception__c];
        System.assertEquals(1, logs.size());
    }
    
}