SunSkyDemo/force-app/main/default/objects/Exception__c/Exception__c.object-meta.xml
<CustomObject>
    <description>Custom object used to store caught exceptions. Workflow rules can be leveraged to send email alerts upon record creation, and Process Builder can be used to send messages to a Chatter group or user.</description>
    <label>Exception</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Exception Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SunSkyDemo/force-app/main/default/objects/Exception__c/fields/Stack_Trace_String__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace_String__c</fullName>
    <label>Stack Trace String</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

SunSkyDemo/force-app/main/default/objects/Exception__c/fields/Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Type_Name__c</fullName>
    <label>Type Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AsyncException</fullName>
            </value>
            <value>
                <fullName>CalloutException</fullName>
            </value>
            <value>
                <fullName>DmlException</fullName>
            </value>
            <value>
                <fullName>EmailException</fullName>
            </value>
            <value>
                <fullName>InvalidParameterValueException</fullName>
            </value>
            <value>
                <fullName>JSONException</fullName>
            </value>
            <value>
                <fullName>LimitException</fullName>
            </value>
            <value>
                <fullName>ListException</fullName>
            </value>
            <value>
                <fullName>MathException</fullName>
            </value>
            <value>
                <fullName>NoAccessException</fullName>
            </value>
            <value>
                <fullName>NoDataFoundException</fullName>
            </value>
            <value>
                <fullName>NullPointerException</fullName>
            </value>
            <value>
                <fullName>QueryException</fullName>
            </value>
            <value>
                <fullName>RequiredFeatureMissing</fullName>
            </value>
            <value>
                <fullName>SearchException</fullName>
            </value>
            <value>
                <fullName>SecurityException</fullName>
            </value>
            <value>
                <fullName>SerializationException</fullName>
            </value>
            <value>
                <fullName>SObjectException</fullName>
            </value>
            <value>
                <fullName>StringException</fullName>
            </value>
            <value>
                <fullName>TypeException</fullName>
            </value>
            <value>
                <fullName>VisualforceException</fullName>
            </value>
            <value>
                <fullName>XmlException</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SunSkyDemo/force-app/main/default/objects/ExceptionEvent__e/ExceptionEvent__e.object-meta.xml
<CustomObject>
    <label>Exception Event</label>
    <pluralLabel>Exception Events</pluralLabel>
</CustomObject>

SunSkyDemo/force-app/main/default/objects/ExceptionEvent__e/fields/Cause__c.field-meta.xml
<CustomField>
    <fullName>Cause__c</fullName>
    <label>Cause</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

SunSkyDemo/force-app/main/default/objects/ExceptionEvent__e/fields/Stack_Trace_String__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace_String__c</fullName>
    <label>Stack Trace String</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

SunSkyDemo/force-app/main/default/objects/ExceptionEvent__e/fields/Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Type_Name__c</fullName>
    <label>Type Name</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

SunSkyDemo/force-app/main/default/classes/ExceptionUtils.cls
global class ExceptionUtils {
    
    global static void handleException(Exception exceptionCaught, Boolean logToObject) {
        
        Exception__c exceptionStaged = new Exception__c();
        
        exceptionStaged.Cause__c = String.valueOf(exceptionCaught.getCause());
        exceptionStaged.Line_Number__c = exceptionCaught.getLineNumber();
        exceptionStaged.Message__c = exceptionCaught.getMessage();
        exceptionStaged.Stack_Trace_String__c = exceptionCaught.getStackTraceString();
        exceptionStaged.Type_Name__c = exceptionCaught.getTypeName();
        
        String exceptionCause = exceptionStaged.Cause__c;
        Decimal exceptionLineNumber = exceptionStaged.Line_Number__c;
        String exceptionMessage = exceptionStaged.Message__c;
        String exceptionStackTraceString = exceptionStaged.Stack_Trace_String__c;
        String exceptionTypeName = exceptionStaged.Type_Name__c;
        
        if(logToObject) {
            ExceptionUtils.logToObject(exceptionStaged);
        }
        
    }    

    
    global static void handleExceptionEvent(Exception exceptionCaught) {
        
        ExceptionEvent__e exceptionStaged = new ExceptionEvent__e();
        
        exceptionStaged.Cause__c = String.valueOf(exceptionCaught.getCause());
        exceptionStaged.Line_Number__c = exceptionCaught.getLineNumber();
        exceptionStaged.Message__c = exceptionCaught.getMessage();
        exceptionStaged.Stack_Trace_String__c = exceptionCaught.getStackTraceString();
        exceptionStaged.Type_Name__c = exceptionCaught.getTypeName();
        
        String exceptionCause = exceptionStaged.Cause__c;
        Decimal exceptionLineNumber = exceptionStaged.Line_Number__c;
        String exceptionMessage = exceptionStaged.Message__c;
        String exceptionStackTraceString = exceptionStaged.Stack_Trace_String__c;
        String exceptionTypeName = exceptionStaged.Type_Name__c;
        Eventbus.publish(exceptionStaged);
        }
           

    private static void logToObject(Exception__c exceptionPassed) {

		List<Exception__c> exceptionsToInsert = new List<Exception__c >();

        exceptionsToInsert.add(exceptionPassed);
        insert exceptionsToInsert;
    }
    
    
}